SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_VERSION 1)

SET(CMAKE_C_COMPILER   /usr/bin/arm-linux-gcc)
SET(CMAKE_CXX_COMPILER /usr/bin/arm-linux-g++)

SET(CMAKE_FIND_ROOT_PATH /opt/chumby)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
